import {Member} from "../interfaces/member";

export const members: Member[] = [
  {
    id: 1,
    name: 'Ishani Roy',
    photo: 'assets/imgs/1.jpg',
    phone: '+91 88888 99999',
    gender: 'Female',
    address: 'Kolkata, India',
    batchName: 'Evening Batch',
    batchTime: '5:30 PM - 7:00 PM',
    trainingType: 'Personal Training',
    package: {
      plan: '1 Year Plan',
      totalAmount: '$600',
      discount: '$60',
      purchaseDate: '01 Jan 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$540',
      dueAmount: '$60',
      daysRemaining: 365,
    },
  },
  {
    id: 2,
    name: 'Sophia Carter',
    photo: 'assets/imgs/2.jpg',
    phone: '+1 123 456 7890',
    gender: 'Female',
    address: 'San Francisco, USA',
    batchName: 'Morning Batch',
    batchTime: '7:00 AM - 8:30 AM',
    trainingType: 'Yoga Training',
    package: {
      plan: '3 Month Plan',
      totalAmount: '$200',
      discount: '$20',
      purchaseDate: '15 Jan 2025',
      planExpiryDate: '15 Apr 2025',
      paid: '$180',
      dueAmount: '$20',
      daysRemaining: 90,
    },
  },
  {
    id: 3,
    name: 'Sneha Desai',
    photo: 'assets/imgs/3.jpg',
    phone: '+91 90909 80808',
    gender: 'Female',
    address: 'Ahmedabad, India',
    batchName: 'Morning Batch',
    batchTime: '7:00 AM - 8:30 AM',
    trainingType: 'Weight Loss Program',
    package: {
      plan: '3 Month Plan',
      totalAmount: '$216',
      discount: '$24',
      purchaseDate: '10 Jan 2024',
      planExpiryDate: '10 Apr 2024',
      paid: '$192',
      dueAmount: '$24',
      daysRemaining: 90,
    },
  },
  {
    id: 4,
    name: 'Aarav Kapoor',
    photo: 'assets/imgs/4.jpg',
    phone: '+91 98765 43210',
    gender: 'Male',
    address: 'Mumbai, India',
    batchName: 'Early Morning Batch',
    batchTime: '6:00 AM - 7:30 AM',
    trainingType: 'General Fitness',
    package: {
      plan: '6 Month Plan',
      totalAmount: '$180',
      discount: '$0',
      purchaseDate: '01 Jan 2024',
      planExpiryDate: '01 Jul 2024',
      paid: '$120',
      dueAmount: '$60',
      daysRemaining: 180,
    },
  },
  {
    id: 5,
    name: "Liam O'Connor",
    photo: 'assets/imgs/5.jpg',
    phone: '+353 87654 3210',
    gender: 'Male',
    address: 'Dublin, Ireland',
    batchName: 'Evening Batch',
    batchTime: '6:00 PM - 7:30 PM',
    trainingType: 'Strength Training',
    package: {
      plan: '6 Month Plan',
      totalAmount: '$320',
      discount: '$0',
      purchaseDate: '15 Jan 2025',
      planExpiryDate: '15 Jul 2025',
      paid: '$270',
      dueAmount: '$50',
      daysRemaining: 180,
    },
  },
  {
    id: 6,
    name: 'Emily Zhang',
    photo: 'assets/imgs/1.jpg',
    phone: '+86 13579 24680',
    gender: 'Female',
    address: 'Beijing, China',
    batchName: 'Afternoon Batch',
    batchTime: '3:00 PM - 4:30 PM',
    trainingType: 'Pilates',
    package: {
      plan: '1 Month Plan',
      totalAmount: '$80',
      discount: '$10',
      purchaseDate: '01 Oct 2025',
      planExpiryDate: '01 Nov 2025',
      paid: '$70',
      dueAmount: '$10',
      daysRemaining: 31,
    },
  },
  {
    id: 7,
    name: 'Carlos Mendez',
    photo: 'assets/imgs/2.jpg',
    phone: '+52 12345 67890',
    gender: 'Male',
    address: 'Mexico City, Mexico',
    batchName: 'Evening Batch',
    batchTime: '6:30 PM - 8:00 PM',
    trainingType: 'CrossFit',
    package: {
      plan: '3 Month Plan',
      totalAmount: '$250',
      discount: '$25',
      purchaseDate: '01 Sep 2025',
      planExpiryDate: '01 Dec 2025',
      paid: '$225',
      dueAmount: '$25',
      daysRemaining: 90,
    },
  },
  {
    id: 8,
    name: 'Fatima El Amrani',
    photo: 'assets/imgs/3.jpg',
    phone: '+212 67890 12345',
    gender: 'Female',
    address: 'Casablanca, Morocco',
    batchName: 'Morning Batch',
    batchTime: '7:30 AM - 9:00 AM',
    trainingType: 'Cardio Training',
    package: {
      plan: '6 Month Plan',
      totalAmount: '$300',
      discount: '$30',
      purchaseDate: '01 Aug 2025',
      planExpiryDate: '01 Feb 2026',
      paid: '$270',
      dueAmount: '$30',
      daysRemaining: 180,
    },
  },
  {
    id: 9,
    name: 'John Smith',
    photo: 'assets/imgs/4.jpg',
    phone: '+1 987 654 3210',
    gender: 'Male',
    address: 'New York, USA',
    batchName: 'Evening Batch',
    batchTime: '5:00 PM - 6:30 PM',
    trainingType: 'HIIT',
    package: {
      plan: '1 Year Plan',
      totalAmount: '$720',
      discount: '$72',
      purchaseDate: '01 Jan 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$648',
      dueAmount: '$72',
      daysRemaining: 365,
    },
  },
  {
    id: 10,
    name: 'Amina Benali',
    photo: 'assets/imgs/5.jpg',
    phone: '+213 55678 1234',
    gender: 'Female',
    address: 'Algiers, Algeria',
    batchName: 'Morning Batch',
    batchTime: '8:00 AM - 9:30 AM',
    trainingType: 'Zumba',
    package: {
      plan: '3 Month Plan',
      totalAmount: '$180',
      discount: '$18',
      purchaseDate: '01 Oct 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$162',
      dueAmount: '$18',
      daysRemaining: 90,
    },
  },
  {
    id: 11,
    name: 'Noah Kim',
    photo: 'assets/imgs/1.jpg',
    phone: '+82 10123 45678',
    gender: 'Male',
    address: 'Seoul, South Korea',
    batchName: 'Afternoon Batch',
    batchTime: '2:00 PM - 3:30 PM',
    trainingType: 'Martial Arts',
    package: {
      plan: '6 Month Plan',
      totalAmount: '$400',
      discount: '$40',
      purchaseDate: '01 Jul 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$360',
      dueAmount: '$40',
      daysRemaining: 180,
    },
  },
  {
    id: 12,
    name: 'Chloe Dubois',
    photo: 'assets/imgs/2.jpg',
    phone: '+33 61234 56789',
    gender: 'Female',
    address: 'Paris, France',
    batchName: 'Evening Batch',
    batchTime: '6:00 PM - 7:30 PM',
    trainingType: 'Dance Fitness',
    package: {
      plan: '3 Month Plan',
      totalAmount: '$240',
      discount: '$30',
      purchaseDate: '01 Oct 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$210',
      dueAmount: '$30',
      daysRemaining: 90,
    },
  },
  {
    id: 13,
    name: 'Mohammed Al-Farsi',
    photo: 'assets/imgs/3.jpg',
    phone: '+971 50123 4567',
    gender: 'Male',
    address: 'Dubai, UAE',
    batchName: 'Morning Batch',
    batchTime: '8:00 AM - 9:30 AM',
    trainingType: 'Bodybuilding',
    package: {
      plan: '1 Year Plan',
      totalAmount: '$900',
      discount: '$90',
      purchaseDate: '01 Jan 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$810',
      dueAmount: '$90',
      daysRemaining: 365,
    },
  },
  {
    id: 14,
    name: 'Isabella Rossi',
    photo: 'assets/imgs/4.jpg',
    phone: '+39 34567 89012',
    gender: 'Female',
    address: 'Rome, Italy',
    batchName: 'Afternoon Batch',
    batchTime: '4:00 PM - 5:30 PM',
    trainingType: 'Aerobics',
    package: {
      plan: '1 Month Plan',
      totalAmount: '$100',
      discount: '$10',
      purchaseDate: '01 Oct 2025',
      planExpiryDate: '01 Nov 2025',
      paid: '$90',
      dueAmount: '$10',
      daysRemaining: 31,
    },
  },
  {
    id: 15,
    name: 'Lucas Müller',
    photo: 'assets/imgs/5.jpg',
    phone: '+49 15123 45678',
    gender: 'Male',
    address: 'Berlin, Germany',
    batchName: 'Early Morning Batch',
    batchTime: '6:00 AM - 7:30 AM',
    trainingType: 'Endurance Training',
    package: {
      plan: '6 Month Plan',
      totalAmount: '$360',
      discount: '$36',
      purchaseDate: '01 Jul 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$324',
      dueAmount: '$36',
      daysRemaining: 180,
    },
  },
  {
    id: 16,
    name: 'Yuki Tanaka',
    photo: 'assets/imgs/1.jpg',
    phone: '+81 90123 45678',
    gender: 'Female',
    address: 'Tokyo, Japan',
    batchName: 'Morning Batch',
    batchTime: '7:00 AM - 8:30 AM',
    trainingType: 'Flexibility Training',
    package: {
      plan: '3 Month Plan',
      totalAmount: '$270',
      discount: '$30',
      purchaseDate: '01 Oct 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$240',
      dueAmount: '$30',
      daysRemaining: 90,
    },
  },
  {
    id: 17,
    name: 'David Johnson',
    photo: 'assets/imgs/2.jpg',
    phone: '+1 555 123 4567',
    gender: 'Male',
    address: 'Chicago, USA',
    batchName: 'Evening Batch',
    batchTime: '5:30 PM - 7:00 PM',
    trainingType: 'Functional Training',
    package: {
      plan: '1 Year Plan',
      totalAmount: '$720',
      discount: '$72',
      purchaseDate: '01 Jan 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$648',
      dueAmount: '$72',
      daysRemaining: 365,
    },
  },
  {
    id: 18,
    name: 'Sara Ahmed',
    photo: 'assets/imgs/3.jpg',
    phone: '+20 10123 45678',
    gender: 'Female',
    address: 'Cairo, Egypt',
    batchName: 'Afternoon Batch',
    batchTime: '3:00 PM - 4:30 PM',
    trainingType: 'Core Strength',
    package: {
      plan: '6 Month Plan',
      totalAmount: '$300',
      discount: '$30',
      purchaseDate: '01 Jul 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$270',
      dueAmount: '$30',
      daysRemaining: 180,
    },
  },
  {
    id: 19,
    name: 'Mateo González',
    photo: 'assets/imgs/4.jpg',
    phone: '+34 61234 56789',
    gender: 'Male',
    address: 'Madrid, Spain',
    batchName: 'Morning Batch',
    batchTime: '8:00 AM - 9:30 AM',
    trainingType: 'Athletic Conditioning',
    package: {
      plan: '3 Month Plan',
      totalAmount: '$240',
      discount: '$24',
      purchaseDate: '01 Oct 2025',
      planExpiryDate: '01 Jan 2026',
      paid: '$216',
      dueAmount: '$24',
      daysRemaining: 90,
    },
  },
  {
    id: 20,
    name: 'Leila Bouzid',
    photo: 'assets/imgs/5.jpg',
    phone: '+213 66123 4567',
    gender: 'Female',
    address: 'Hydra, Algeria',
    batchName: 'Evening Batch',
    batchTime: '6:00 PM - 7:30 PM',
    trainingType: 'Wellness Coaching',
    package: {
      plan: '1 Year Plan',
      totalAmount: '$600',
      discount: '$60',
      purchaseDate: '01 Oct 2025',
      planExpiryDate: '01 Oct 2026',
      paid: '$540',
      dueAmount: '$60',
      daysRemaining: 365,
    },
  },
];
